services:
  react-native:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    command: npm start